version: '3.8'

services:
  countryflag-api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: countryflag-api:latest
    container_name: countryflag-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - ENABLE_CACHE=true
      - CACHE_TTL=3600
    volumes:
      - countryflag-cache:/app/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  countryflag-web:
    image: nginx:alpine
    container_name: countryflag-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../web:/usr/share/nginx/html:ro
    depends_on:
      - countryflag-api

  # Optional Redis cache for high-performance deployments
  redis:
    image: redis:alpine
    container_name: countryflag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  countryflag-cache:
  redis-data:
