apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: countryflag-monitor
  labels:
    app: countryflag
    release: prometheus
spec:
  selector:
    matchLabels:
      app: countryflag
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
